### ISSUE TITLE
Error when running the backend

### ISSUE THREAD

**Issue by enimiste** [Emmanuel0110/dojo-app#9]
When i run the command : `node index.js` i got this error :

```
MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
    at _handleConnectionErrors (/workspaces/JavaScript/dojo-app/backend/node_modules/mongoose/lib/connection.js:809:11)
    at NativeConnection.openUri (/workspaces/JavaScript/dojo-app/backend/node_modules/mongoose/lib/connection.js:784:11) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
```

**Comment by Emmanuel0110** [comment]
Right, I forgot to mention the .env files to put in backend (including mongodb credentials) and frontend directories. I just modified readme file
